package guanarentjc.vista;

import guanarentjc.modelo.Alquileres;
import guanarentjc.modelo.Datos;
import guanarentjc.modelo.Inquilino;
import guanarentjc.modelo.Vivienda;
import java.time.LocalDate;
import javax.swing.JOptionPane;

/**
 * Diálogo para insertar o editar un {@link Alquileres}. Si se construye con
 * un alquiler existente, edita ese registro; si se construye con
 * {@code null}, crea uno nuevo.
 */
public class DlgAlquiler extends javax.swing.JDialog {

    private final Datos datos = Datos.getInstancia();
    private final Alquileres existente;
    private boolean guardado = false;

    public DlgAlquiler(java.awt.Frame parent, boolean modal, Alquileres existente) {
        super(parent, modal);
        this.existente = existente;
        initComponents();

        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(
                new String[]{Alquileres.ESTADO_VIGENTE, Alquileres.ESTADO_VENCIDO, Alquileres.ESTADO_CANCELADO}));
        cargarListas();

        if (existente != null) {
            setTitle("Editar Alquiler");
            txtNumAlquiler.setText(String.valueOf(existente.getNumAlquiler()));
            txtNumAlquiler.setEditable(false);
            dtpFechaContrato.setDate(existente.getFechContrato());
            txtCantMeses.setText(String.valueOf(existente.getCantMeses()));
            txtNumAdultos.setText(String.valueOf(existente.getNumAdultos()));
            txtNumNinos.setText(String.valueOf(existente.getNumNinos()));
            txtDepositoGarantia.setText(String.valueOf(existente.getDepositoGarantia()));
            txtPrecioAlquiler.setText(String.valueOf(existente.getPrecioAlquiler()));
            txtPorcIncremAnual.setText(String.valueOf(existente.getPorcIncremAnual()));
            Inquilino inq = datos.buscarInquilino(existente.getCedInquilino());
            if (inq != null) {
                cmbInquilino.setSelectedItem(inq);
            }
            Vivienda viv = datos.buscarVivienda(existente.getIdVivienda());
            if (viv != null) {
                cmbVivienda.setSelectedItem(viv);
            }
            cmbEstado.setSelectedItem(existente.getEstado());
        } else {
            setTitle("Nuevo Alquiler");
            txtNumAlquiler.setText(String.valueOf(datos.siguienteNumAlquiler()));
        }

        setLocationRelativeTo(parent);
    }

    public boolean isGuardado() {
        return guardado;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNumAlquiler = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        dtpFechaContrato = new com.github.lgooddatepicker.components.DatePicker();
        jLabel3 = new javax.swing.JLabel();
        txtCantMeses = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNumAdultos = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNumNinos = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtDepositoGarantia = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtPrecioAlquiler = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtPorcIncremAnual = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cmbInquilino = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        cmbVivienda = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        cmbEstado = new javax.swing.JComboBox<>();
        btnGuardar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alquiler");
        setResizable(false);

        jLabel1.setText("Núm. alquiler:");
        jLabel2.setText("Fecha contrato:");
        jLabel3.setText("Cant. meses:");
        jLabel4.setText("Núm. adultos:");
        jLabel5.setText("Núm. niños:");
        jLabel6.setText("Depósito garantía:");
        jLabel7.setText("Precio alquiler:");
        jLabel8.setText("% Increm. anual (1-30):");
        jLabel9.setText("Inquilino:");
        jLabel10.setText("Vivienda:");
        jLabel11.setText("Estado:");

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/guardar.png")));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/limpiar.png")));
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png")));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumAlquiler, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantMeses, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumNinos, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrecioAlquiler, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbInquilino, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dtpFechaContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumAdultos, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDepositoGarantia, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPorcIncremAnual, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbVivienda, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(0, Short.MAX_VALUE)
                .addComponent(btnGuardar)
                .addGap(10, 10, 10)
                .addComponent(btnLimpiar)
                .addGap(10, 10, 10)
                .addComponent(btnCancelar)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtNumAlquiler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(dtpFechaContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtCantMeses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtNumAdultos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtNumNinos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtDepositoGarantia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txtPrecioAlquiler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtPorcIncremAnual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(cmbInquilino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(cmbVivienda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGuardar)
                    .addComponent(btnLimpiar)
                    .addComponent(btnCancelar))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {
        guardar();
    }

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {
        limpiarFormulario();
    }

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {
        dispose();
    }

    private void cargarListas() {
        Datos.recargarCombo(cmbInquilino, datos.getInquilinos());
        Datos.recargarCombo(cmbVivienda, datos.getViviendas());
    }

    private void guardar() {
        try {
            int numAlquiler = Integer.parseInt(txtNumAlquiler.getText().trim());
            LocalDate fecha = dtpFechaContrato.getDate();
            if (fecha == null) {
                JOptionPane.showMessageDialog(this, "Debe seleccionar la fecha de contrato", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            int cantMeses = Integer.parseInt(txtCantMeses.getText().trim());
            int numAdultos = Integer.parseInt(txtNumAdultos.getText().trim());
            int numNinos = Integer.parseInt(txtNumNinos.getText().trim());
            double depositoGarantia = Double.parseDouble(txtDepositoGarantia.getText().trim());
            double precioAlquiler = Double.parseDouble(txtPrecioAlquiler.getText().trim());
            double porcIncremAnual = Double.parseDouble(txtPorcIncremAnual.getText().trim());

            if (porcIncremAnual < 1 || porcIncremAnual > 30) {
                JOptionPane.showMessageDialog(this, "El % de incremento anual debe estar entre 1 y 30", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (cmbInquilino.getSelectedItem() == null || cmbVivienda.getSelectedItem() == null) {
                JOptionPane.showMessageDialog(this, "Debe seleccionar inquilino y vivienda", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            Inquilino inquilino = (Inquilino) cmbInquilino.getSelectedItem();
            Vivienda vivienda = (Vivienda) cmbVivienda.getSelectedItem();
            String estado = (String) cmbEstado.getSelectedItem();

            if (existente == null) {
                Alquileres a = new Alquileres(numAlquiler, fecha, cantMeses, numAdultos, numNinos, depositoGarantia,
                        precioAlquiler, porcIncremAnual, inquilino.getCedInqui(), vivienda.getIdVivienda(), estado);
                datos.insertarAlquiler(a);
            } else {
                existente.setFechContrato(fecha);
                existente.setCantMeses(cantMeses);
                existente.setNumAdultos(numAdultos);
                existente.setNumNinos(numNinos);
                existente.setDepositoGarantia(depositoGarantia);
                existente.setPrecioAlquiler(precioAlquiler);
                existente.setPorcIncremAnual(porcIncremAnual);
                existente.setCedInquilino(inquilino.getCedInqui());
                existente.setIdVivienda(vivienda.getIdVivienda());
                existente.setEstado(estado);
            }
            guardado = true;
            dispose();
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Revise que los campos numéricos tengan valores válidos", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void limpiarFormulario() {
        dtpFechaContrato.setDate(null);
        txtCantMeses.setText("");
        txtNumAdultos.setText("");
        txtNumNinos.setText("");
        txtDepositoGarantia.setText("");
        txtPrecioAlquiler.setText("");
        txtPorcIncremAnual.setText("");
        cmbEstado.setSelectedIndex(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JComboBox<Inquilino> cmbInquilino;
    private javax.swing.JComboBox<Vivienda> cmbVivienda;
    private com.github.lgooddatepicker.components.DatePicker dtpFechaContrato;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtCantMeses;
    private javax.swing.JTextField txtDepositoGarantia;
    private javax.swing.JTextField txtNumAdultos;
    private javax.swing.JTextField txtNumAlquiler;
    private javax.swing.JTextField txtNumNinos;
    private javax.swing.JTextField txtPorcIncremAnual;
    private javax.swing.JTextField txtPrecioAlquiler;
    // End of variables declaration//GEN-END:variables
}
