package guanarentjc.vista;

import guanarentjc.modelo.Datos;
import java.time.LocalDate;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 * Módulo de Ganancias: permite consultar lo que GuanaRent ganó en un año
 * completo o en un mes específico. GuanaRent gana la mitad del depósito de
 * garantía de cada alquiler firmado, más un 7% de cada mensualidad cobrada.
 */
public class DlgGanancias extends javax.swing.JDialog {

    private static final String[] MESES = {"Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio",
        "Julio", "Agosto", "Setiembre", "Octubre", "Noviembre", "Diciembre"};

    private final Datos datos = Datos.getInstancia();

    public DlgGanancias(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        ButtonGroup grupo = new ButtonGroup();
        grupo.add(rbAnual);
        grupo.add(rbMensual);
        rbAnual.setSelected(true);
        rbAnual.addActionListener(e -> cmbMes.setEnabled(false));
        rbMensual.addActionListener(e -> cmbMes.setEnabled(true));

        cmbMes.setModel(new javax.swing.DefaultComboBoxModel<>(MESES));
        cmbMes.setEnabled(false);
        txtAnio.setText(String.valueOf(LocalDate.now().getYear()));
        lblResultado.setFont(lblResultado.getFont().deriveFont(java.awt.Font.BOLD, 16f));

        setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbAnual = new javax.swing.JRadioButton();
        rbMensual = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        cmbMes = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtAnio = new javax.swing.JTextField();
        btnConsultar = new javax.swing.JButton();
        lblResultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ganancias de GuanaRent");
        setResizable(false);

        rbAnual.setText("Ganancias de todo un año");
        rbMensual.setText("Ganancias de un mes específico");
        jLabel1.setText("Mes:");
        jLabel2.setText("Año:");

        btnConsultar.setText("Consultar ganancias");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        lblResultado.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbAnual)
                    .addComponent(rbMensual)
                    .addComponent(lblResultado)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbMes, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnConsultar))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(rbAnual)
                .addGap(6, 6, 6)
                .addComponent(rbMensual)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(cmbMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(btnConsultar)
                .addGap(12, 12, 12)
                .addComponent(lblResultado)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {
        consultar();
    }

    private void consultar() {
        try {
            int anio = Integer.parseInt(txtAnio.getText().trim());
            double ganancia;
            if (rbAnual.isSelected()) {
                ganancia = datos.gananciaAnual(anio);
                lblResultado.setText(String.format("Ganancia del año %d: ₡%,.2f", anio, ganancia));
            } else {
                int mes = cmbMes.getSelectedIndex() + 1;
                ganancia = datos.gananciaMensual(mes, anio);
                lblResultado.setText(String.format("Ganancia de %s %d: ₡%,.2f", MESES[mes - 1], anio, ganancia));
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "El año debe ser numérico", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultar;
    private javax.swing.JComboBox<String> cmbMes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JRadioButton rbAnual;
    private javax.swing.JRadioButton rbMensual;
    private javax.swing.JTextField txtAnio;
    // End of variables declaration//GEN-END:variables
}
