package guanarentjc.vista;

import guanarentjc.modelo.Alquileres;
import guanarentjc.modelo.Datos;
import guanarentjc.modelo.Inquilino;
import guanarentjc.modelo.Vivienda;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * Ventana de gestión de alquileres: búsqueda, tabla y acceso a Insertar,
 * Editar y Eliminar (que abren {@link DlgAlquiler}).
 */
public class DlgMainAlquileres extends javax.swing.JDialog {

    private static final DateTimeFormatter FORMATO_FECHA = DateTimeFormatter.ofPattern("dd/MM/yyyy");

    private final Datos datos = Datos.getInstancia();
    private DefaultTableModel modeloTabla;

    public DlgMainAlquileres(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        modeloTabla = new DefaultTableModel(new Object[]{"Núm.", "Fecha contrato", "Meses", "Inquilino",
            "Vivienda", "Precio", "Depósito", "% Increm.", "Estado"}, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tabla.setModel(modeloTabla);

        setLocationRelativeTo(parent);
        refrescarTabla(datos.getAlquileres());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnInsertar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestión de Alquileres");

        jLabel1.setText("Buscar:");

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });

        btnInsertar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/agregar.png")));
        btnInsertar.setText("Insertar");
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/editar.png")));
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminar.png")));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(tabla);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(6, 6, 6)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnInsertar)
                        .addGap(10, 10, 10)
                        .addComponent(btnEditar)
                        .addGap(10, 10, 10)
                        .addComponent(btnEliminar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 850, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInsertar)
                    .addComponent(btnEditar)
                    .addComponent(btnEliminar))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {
        DlgAlquiler dlg = new DlgAlquiler((java.awt.Frame) getParent(), true, null);
        dlg.setVisible(true);
        if (dlg.isGuardado()) {
            refrescarTabla(datos.getAlquileres());
        }
    }

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {
        Alquileres a = obtenerSeleccionado();
        if (a == null) {
            JOptionPane.showMessageDialog(this, "Seleccione un alquiler de la tabla", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        DlgAlquiler dlg = new DlgAlquiler((java.awt.Frame) getParent(), true, a);
        dlg.setVisible(true);
        if (dlg.isGuardado()) {
            refrescarTabla(datos.getAlquileres());
        }
    }

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {
        Alquileres a = obtenerSeleccionado();
        if (a == null) {
            JOptionPane.showMessageDialog(this, "Seleccione un alquiler de la tabla", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        int resp = JOptionPane.showConfirmDialog(this, "¿Eliminar alquiler #" + a.getNumAlquiler() + "?", "Confirmar", JOptionPane.YES_NO_OPTION);
        if (resp != JOptionPane.YES_OPTION) {
            return;
        }
        try {
            datos.eliminarAlquiler(a.getNumAlquiler());
            refrescarTabla(datos.getAlquileres());
        } catch (IllegalStateException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {
        filtrar();
    }

    private void filtrar() {
        String texto = txtBuscar.getText().trim().toLowerCase();
        if (texto.isEmpty()) {
            refrescarTabla(datos.getAlquileres());
            return;
        }
        java.util.List<Alquileres> filtrados = datos.getAlquileres().stream()
                .filter(a -> String.valueOf(a.getNumAlquiler()).contains(texto)
                        || a.getEstado().toLowerCase().contains(texto))
                .toList();
        refrescarTabla(filtrados);
    }

    private Alquileres obtenerSeleccionado() {
        int fila = tabla.getSelectedRow();
        if (fila < 0) {
            return null;
        }
        int num = (Integer) modeloTabla.getValueAt(fila, 0);
        return datos.buscarAlquiler(num);
    }

    private void refrescarTabla(java.util.List<Alquileres> lista) {
        modeloTabla.setRowCount(0);
        for (Alquileres a : lista) {
            Inquilino inq = datos.buscarInquilino(a.getCedInquilino());
            Vivienda viv = datos.buscarVivienda(a.getIdVivienda());
            modeloTabla.addRow(new Object[]{a.getNumAlquiler(),
                a.getFechContrato() != null ? a.getFechContrato().format(FORMATO_FECHA) : "",
                a.getCantMeses(), inq != null ? inq.getNomInqui() : a.getCedInquilino(),
                viv != null ? viv.getDescripcion() : a.getIdVivienda(), a.getPrecioAlquiler(),
                a.getDepositoGarantia(), a.getPorcIncremAnual(), a.getEstado()});
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
