package guanarentjc.vista;

import guanarentjc.modelo.Datos;
import guanarentjc.modelo.Mensualidades;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * Módulo de Gestión de Mensualidades: genera automáticamente los recibos de
 * cobro de un mes/año para todos los alquileres vigentes, y permite
 * mostrarlos/filtrarlos.
 */
public class DlgMensualidades extends javax.swing.JDialog {

    private static final DateTimeFormatter FORMATO_FECHA = DateTimeFormatter.ofPattern("dd/MM/yyyy");
    private static final String[] MESES = {"Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio",
        "Julio", "Agosto", "Setiembre", "Octubre", "Noviembre", "Diciembre"};

    private final Datos datos = Datos.getInstancia();
    private DefaultTableModel modeloTabla;

    public DlgMensualidades(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        cmbMesGenerar.setModel(new javax.swing.DefaultComboBoxModel<>(MESES));
        cmbMesMostrar.setModel(new javax.swing.DefaultComboBoxModel<>(MESES));
        txtAnioGenerar.setText(String.valueOf(LocalDate.now().getYear()));
        txtAnioMostrar.setText(String.valueOf(LocalDate.now().getYear()));

        modeloTabla = new DefaultTableModel(new Object[]{"Consecutivo", "Núm. Alquiler", "Fecha Creación",
            "Inquilino", "Mes en cobro", "Año", "Descuento", "Monto a pagar", "Estado"}, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tabla.setModel(modeloTabla);

        setLocationRelativeTo(parent);
        refrescarTabla(datos.getMensualidades());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbMesGenerar = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtAnioGenerar = new javax.swing.JTextField();
        btnGenerar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cmbMesMostrar = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtAnioMostrar = new javax.swing.JTextField();
        btnMostrar = new javax.swing.JButton();
        chkFiltrarInquilino = new javax.swing.JCheckBox();
        chkFiltrarMes = new javax.swing.JCheckBox();
        chkFiltrarAnio = new javax.swing.JCheckBox();
        txtFiltro = new javax.swing.JTextField();
        btnFiltrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestión de Mensualidades");

        jLabel1.setText("Mes:");
        jLabel2.setText("Año:");

        btnGenerar.setText("Generar");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });

        jLabel3.setText("Mes:");
        jLabel4.setText("Año:");

        btnMostrar.setText("Mostrar");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        chkFiltrarInquilino.setText("Inquilino");
        chkFiltrarMes.setText("Mes");
        chkFiltrarAnio.setText("Año");

        btnFiltrar.setText("Filtrar");
        btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(tabla);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbMesGenerar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAnioGenerar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbMesMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAnioMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(btnGenerar)
                .addGap(10, 10, 10)
                .addComponent(btnMostrar)
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(chkFiltrarInquilino)
                .addGap(8, 8, 8)
                .addComponent(chkFiltrarMes)
                .addGap(8, 8, 8)
                .addComponent(chkFiltrarAnio)
                .addGap(8, 8, 8)
                .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(btnFiltrar)
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 900, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(cmbMesGenerar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtAnioGenerar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGenerar))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(cmbMesMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtAnioMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMostrar))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkFiltrarInquilino)
                    .addComponent(chkFiltrarMes)
                    .addComponent(chkFiltrarAnio)
                    .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFiltrar))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {
        generar();
    }

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {
        mostrarPorMesAnio();
    }

    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {
        aplicarFiltro();
    }

    private void generar() {
        try {
            int mes = cmbMesGenerar.getSelectedIndex() + 1;
            int anio = Integer.parseInt(txtAnioGenerar.getText().trim());
            int cantidad = datos.generarMensualidades(mes, anio);
            refrescarTabla(datos.getMensualidades());
            JOptionPane.showMessageDialog(this, "Se generaron " + cantidad + " recibos de mensualidad");
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "El año debe ser numérico", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (IllegalArgumentException | IllegalStateException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void mostrarPorMesAnio() {
        try {
            int mes = cmbMesMostrar.getSelectedIndex() + 1;
            int anio = Integer.parseInt(txtAnioMostrar.getText().trim());
            java.util.List<Mensualidades> lista = datos.getMensualidades().stream()
                    .filter(m -> m.getMesCobro() == mes && m.getAnioActual() == anio)
                    .toList();
            refrescarTabla(lista);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "El año debe ser numérico", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void aplicarFiltro() {
        String texto = txtFiltro.getText().trim();
        if (texto.isEmpty()) {
            refrescarTabla(datos.getMensualidades());
            return;
        }
        java.util.List<Mensualidades> lista = datos.getMensualidades().stream()
                .filter(m -> {
                    if (chkFiltrarInquilino.isSelected() && m.getNomInquilino().toLowerCase().contains(texto.toLowerCase())) {
                        return true;
                    }
                    if (chkFiltrarMes.isSelected() && MESES[m.getMesCobro() - 1].equalsIgnoreCase(texto)) {
                        return true;
                    }
                    if (chkFiltrarAnio.isSelected() && String.valueOf(m.getAnioActual()).equals(texto)) {
                        return true;
                    }
                    return false;
                })
                .toList();
        refrescarTabla(lista);
    }

    private void refrescarTabla(java.util.List<Mensualidades> lista) {
        modeloTabla.setRowCount(0);
        for (Mensualidades m : lista) {
            modeloTabla.addRow(new Object[]{m.getConsecutivo(), m.getNumAlquiler(),
                m.getFechCreacion() != null ? m.getFechCreacion().format(FORMATO_FECHA) : "",
                m.getNomInquilino(), MESES[m.getMesCobro() - 1], m.getAnioActual(),
                m.getDescuento(), m.getMontoMes(), m.getEstado()});
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JButton btnGenerar;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JCheckBox chkFiltrarAnio;
    private javax.swing.JCheckBox chkFiltrarInquilino;
    private javax.swing.JCheckBox chkFiltrarMes;
    private javax.swing.JComboBox<String> cmbMesGenerar;
    private javax.swing.JComboBox<String> cmbMesMostrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtAnioGenerar;
    private javax.swing.JTextField txtAnioMostrar;
    private javax.swing.JTextField txtFiltro;
    // End of variables declaration//GEN-END:variables
}
