package guanarentjc.vista;

import guanarentjc.modelo.Datos;
import guanarentjc.modelo.Propietario;
import guanarentjc.modelo.Vivienda;
import javax.swing.JOptionPane;

/**
 * Diálogo para insertar o editar una {@link Vivienda}. Si se construye con
 * una vivienda existente, edita ese registro; si se construye con
 * {@code null}, crea uno nuevo.
 */
public class DlgVivienda extends javax.swing.JDialog {

    private final Datos datos = Datos.getInstancia();
    private final Vivienda existente;
    private boolean guardado = false;

    public DlgVivienda(java.awt.Frame parent, boolean modal, Vivienda existente) {
        super(parent, modal);
        this.existente = existente;
        initComponents();

        cmbTipoConstruccion.setModel(new javax.swing.DefaultComboBoxModel<>(
                new String[]{"Block", "Baldosa", "Super block", "Madera", "Mixta"}));
        cmbCarretera.setModel(new javax.swing.DefaultComboBoxModel<>(
                new String[]{"Lastre", "Pavimentada", "Adoquinada"}));
        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(
                new String[]{Vivienda.ESTADO_DISPONIBLE, Vivienda.ESTADO_ALQUILADA, Vivienda.ESTADO_INACTIVA}));
        cargarPropietarios();

        if (existente != null) {
            setTitle("Editar Vivienda");
            txtId.setText(String.valueOf(existente.getIdVivienda()));
            txtId.setEditable(false);
            txtDescripcion.setText(existente.getDescripcion());
            txtDireccion.setText(existente.getDireccion());
            cmbTipoConstruccion.setSelectedItem(existente.getTipoConstruccion());
            txtMtsConstrucc.setText(String.valueOf(existente.getMtsConstrucc()));
            txtMtsLote.setText(String.valueOf(existente.getMtsLote()));
            chkCochera.setSelected(existente.isCochera());
            txtCantHabitac.setText(String.valueOf(existente.getCantHabitac()));
            txtCantBanios.setText(String.valueOf(existente.getCantBanios()));
            cmbCarretera.setSelectedItem(existente.getCarretera());
            txtPrecioBase.setText(String.valueOf(existente.getPrecioBase()));
            txtDepositoGarantia.setText(String.valueOf(existente.getDepositoGarantia()));
            if (existente.getPropietario() != null) {
                cmbPropietario.setSelectedItem(existente.getPropietario());
            }
            cmbEstado.setSelectedItem(existente.getEstado());
        } else {
            setTitle("Nueva Vivienda");
            txtId.setText(String.valueOf(datos.siguienteIdVivienda()));
        }

        setLocationRelativeTo(parent);
    }

    public boolean isGuardado() {
        return guardado;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cmbTipoConstruccion = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtMtsConstrucc = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtMtsLote = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        chkCochera = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        txtCantHabitac = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtCantBanios = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cmbCarretera = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        txtPrecioBase = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtDepositoGarantia = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cmbPropietario = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        cmbEstado = new javax.swing.JComboBox<>();
        btnGuardar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Vivienda");
        setResizable(false);

        jLabel1.setText("Id vivienda:");
        jLabel2.setText("Descripción:");
        jLabel3.setText("Dirección:");
        jLabel4.setText("Tipo construcción:");
        jLabel5.setText("Mts construcción:");
        jLabel6.setText("Mts lote:");
        jLabel7.setText("Cochera:");
        chkCochera.setText("Tiene cochera");
        jLabel8.setText("Cant. habitaciones:");
        jLabel9.setText("Cant. baños:");
        jLabel10.setText("Carretera:");
        jLabel11.setText("Precio base:");
        jLabel12.setText("Depósito garantía:");
        jLabel13.setText("Propietario:");
        jLabel14.setText("Estado:");

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/guardar.png")));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/limpiar.png")));
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png")));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMtsConstrucc, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkCochera, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantBanios, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrecioBase, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbTipoConstruccion, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMtsLote, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantHabitac, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbCarretera, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDepositoGarantia, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(0, Short.MAX_VALUE)
                .addComponent(btnGuardar)
                .addGap(10, 10, 10)
                .addComponent(btnLimpiar)
                .addGap(10, 10, 10)
                .addComponent(btnCancelar)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(cmbTipoConstruccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtMtsConstrucc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtMtsLote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(chkCochera)
                    .addComponent(jLabel8)
                    .addComponent(txtCantHabitac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(txtCantBanios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(cmbCarretera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(txtPrecioBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txtDepositoGarantia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(cmbPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGuardar)
                    .addComponent(btnLimpiar)
                    .addComponent(btnCancelar))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {
        guardar();
    }

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {
        limpiarFormulario();
    }

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {
        dispose();
    }

    private void cargarPropietarios() {
        Datos.recargarCombo(cmbPropietario, datos.getPropietarios());
    }

    private void guardar() {
        try {
            int id = Integer.parseInt(txtId.getText().trim());
            if (txtDescripcion.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "La descripción es obligatoria", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (cmbPropietario.getSelectedItem() == null) {
                JOptionPane.showMessageDialog(this, "Debe seleccionar un propietario", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            double mtsConstrucc = Double.parseDouble(txtMtsConstrucc.getText().trim());
            double mtsLote = Double.parseDouble(txtMtsLote.getText().trim());
            int cantHabitac = Integer.parseInt(txtCantHabitac.getText().trim());
            double cantBanios = Double.parseDouble(txtCantBanios.getText().trim());
            double precioBase = Double.parseDouble(txtPrecioBase.getText().trim());
            double depositoGarantia = Double.parseDouble(txtDepositoGarantia.getText().trim());
            Propietario propietario = (Propietario) cmbPropietario.getSelectedItem();
            String tipoConstruccion = (String) cmbTipoConstruccion.getSelectedItem();
            String carretera = (String) cmbCarretera.getSelectedItem();
            String estado = (String) cmbEstado.getSelectedItem();

            if (existente == null) {
                Vivienda v = new Vivienda(id, txtDescripcion.getText().trim(), txtDireccion.getText().trim(),
                        mtsConstrucc, mtsLote, tipoConstruccion, chkCochera.isSelected(), cantHabitac, cantBanios,
                        carretera, precioBase, depositoGarantia, propietario, estado);
                datos.insertarVivienda(v);
            } else {
                existente.setDescripcion(txtDescripcion.getText().trim());
                existente.setDireccion(txtDireccion.getText().trim());
                existente.setMtsConstrucc(mtsConstrucc);
                existente.setMtsLote(mtsLote);
                existente.setTipoConstruccion(tipoConstruccion);
                existente.setCochera(chkCochera.isSelected());
                existente.setCantHabitac(cantHabitac);
                existente.setCantBanios(cantBanios);
                existente.setCarretera(carretera);
                existente.setPrecioBase(precioBase);
                existente.setDepositoGarantia(depositoGarantia);
                existente.setPropietario(propietario);
                existente.setEstado(estado);
            }
            guardado = true;
            dispose();
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Revise que los campos numéricos tengan valores válidos", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void limpiarFormulario() {
        txtDescripcion.setText("");
        txtDireccion.setText("");
        cmbTipoConstruccion.setSelectedIndex(0);
        txtMtsConstrucc.setText("");
        txtMtsLote.setText("");
        chkCochera.setSelected(false);
        txtCantHabitac.setText("");
        txtCantBanios.setText("");
        cmbCarretera.setSelectedIndex(0);
        txtPrecioBase.setText("");
        txtDepositoGarantia.setText("");
        cmbEstado.setSelectedIndex(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JCheckBox chkCochera;
    private javax.swing.JComboBox<String> cmbCarretera;
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JComboBox<Propietario> cmbPropietario;
    private javax.swing.JComboBox<String> cmbTipoConstruccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtCantBanios;
    private javax.swing.JTextField txtCantHabitac;
    private javax.swing.JTextField txtDepositoGarantia;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtMtsConstrucc;
    private javax.swing.JTextField txtMtsLote;
    private javax.swing.JTextField txtPrecioBase;
    // End of variables declaration//GEN-END:variables
}
